#***************************************************************************
#
#  The Contents of this file are made available subject to the terms of
#  either of the following licenses
#
#         - GNU Lesser General Public License Version 2.1
#         - Sun Industry Standards Source License Version 1.1
#
#  Sun Microsystems Inc., October, 2000
#
#  GNU Lesser General Public License Version 2.1
#  =============================================
#  Copyright 2000 by Sun Microsystems, Inc.
#  901 San Antonio Road, Palo Alto, CA 94303, USA
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License version 2.1, as published by the Free Software Foundation.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
#  MA  02111-1307  USA
#
#
#  Sun Industry Standards Source License Version 1.1
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.1 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://www.openoffice.org/license.html.
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2000 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
#  Contributor(s): _______________________________________
#
#***************************************************************************


#
#  resources.properties
#
#  resources for org.openoffice.xmerge.converter package.
#
NULL_MIME_EXCEPTION=Cannot specify null MIME types
EMPTY_MIME_EXCEPTION=Cannot specify empty MIME types
CANNOT_LOAD_CLASS=Unable to load class
CANNOT_INST_CLASS=Unable to instantiate class
NOT_AN_INSTANCE= is not an instance of
CANNOT_FIND_REGISTERED=Cannot find registered class
PARSE_ERROR=Parse Error
LINE=Line
COLUMN=Column
PUBLIC_ID=PublicId
SYSTEM_ID=SystemId
INVALID_LOG_LEVEL=Invalid log level specified
OPERATION_NOT_SUPPORTED=Operation not supported
TEMPLATE_FILE_LOAD_ERROR=Error in loading template file -

#
# diff/merge algorithm erro messages
#
EMPTY_NODE_EXCEPTION=Current Node is empty
NOT_LEAFNODE_EXCEPTION=Current Node is not a leaf node
ROOTNODE_EXCEPTION=Cannot perform insert/append/remove on root node
NOT_TEXTNODE_EXCEPTION=The target Node is not a TEXT_NODE, it is -
NULL_NODE_EXCEPTION=The initial Xmldocument node is null
CELL_NODE_EXCEPTION1=Cell node do not have only 1 child <text:p> nodes, will skip the merge of this node.Num of PARA child nodes:
CELL_NODE_EXCEPTION2=Cell node have a non Element child nodes -
CELL_NODE_EXCEPTION2=There is a child node under an expected empty cell node.
NOT_ELEM_NODE_ERROR=The compared nodes are not a Element Node
NOT_PARA_NODE_ERROR=The compared nodes are not a Paragraph or Heading node -
NOT_NODE_ERROR=The compared nodes are not a Node
#
# SXW to/from DOC conversion error messages.
#
UNKNOWN_DOC_VERSION=Unknown DOC version.
DOC_TEXT_LENGTH_EXCEEDED=DOC text length exceeds maximum value.
DOC_TEXT_RECORD_SIZE_EXCEEDED=DOC text record exceeds size limit.
